=== project-lux/data-pipeline/configs/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "type": { "type": "string", "enum": ["external", "internal"] },
    "namespace": { "type": "string", "format": "uri" },
    "matches": {
      "type": "array",
      "items": { "type": "string" }
    },
    "wikidata_property": {
      "type": "array",
      "items": { "type": "string", "minLength": 0 }
    },
    "merge_order": {
      "type": ["integer", "null"],
      "minimum": 1
    },
    "mapSizeExponent": {
      "type": ["integer", "null"],
      "minimum": 1
    },
    "fetch": { "type": "string", "format": "uri-template" },
    "activitystreams": {
      "type": ["array", "null"],
      "items": {
        "type": "string",
        "format": "uri",
        "minLength": 0
      }
    },
    "harvesterClass": {"type": "string", "minLength": 0},    
    "fetcherClass": { "type": "string", "minLength": 0},
    "loaderClass": { "type": "string", "minLength": 0 },
    "indexLoaderClass": { "type": "string", "minLength": 0},
    "mapperClass": { "type": "string", "minLength": 0 },
    "reconcilerClass": { "type": "string", "minLength": 0},


    "cycleBreakPath": { "type": "string", "pattern": "\\.json$|^$", "minLength": 0 },
    "dumpFilePath": { "type": "string", "pattern": "\\.(jsonld|json|tar)\\.gz$|\\.jsonld$|\\.json$|\\.marcxml\\.zip$|\\.db$|\\.xml\\.gz$|^$", "minLength": 0 },
    "remoteDumpFile": { "type": "string", "format": "uri", "minLength": 0 },
    "externalLinksPath": { "type": "string", "minLength": 0 },
    "reconcileDumpPath": { "type": "string", "minLength": 0 },
    "reconcileDbPath": { "type": "string", "minLength": 0 },
    "inverseEquivDbPath": { "type": "string", "pattern": "\\.lmdb$|^$", "minLength": 0 },
    "dump_file_subdir": { "type": "string", "minLength": 0 },
    "remote_dump_files": {
      "type": "array",
      "items": { "type": "string", "format": "uri", "minLength": 0 }
    }
  },
  "required": [
    "name",
    "type",
    "namespace",
    "matches",
    "wikidata_property",
    "merge_order",
    "mapSizeExponent",
    "fetch",
    "activitystreams",
    "harvesterClass",
    "fetcherClass",
    "loaderClass",
    "indexLoaderClass",
    "mapperClass",
    "reconcilerClass",
    "cycleBreakPath",
    "dumpFilePath",
    "remoteDumpFile",
    "externalLinksPath",
    "reconcileDumpPath",
    "reconcileDbPath",
    "inverseEquivDbPath",
    "dump_file_subdir",
    "remote_dump_files"
],
  "additionalProperties": false
}

=== project-lux/data-pipeline/configs/gbif.json
{
    "name": "gbif",
    "type": "external",
    "namespace": "https://www.gbif.org/species/",
    "matches": ["www.gbif.org/species/"],
    "wikidata_property": ["P846"],
    "merge_order": 31,
    "mapSizeExponent": null,
    "fetch": "https://api.gbif.org/v1/species/{identifier}",
    "activitystreams": null,
    
    "harvesterClass": "",
    "fetcherClass": "process.base.fetcher.Fetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.authorities.gbif.mapper.GbifMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "",
    "remote_dump_files": []

}

=== project-lux/data-pipeline/configs/snac.json
{
    "name": "snac",
    "type": "external",
    "namespace": "https://snaccooperative.org",
    "matches": ["http://n2t.net/ark:/99166/"],
    "wikidata_property": ["P3430"],
    "merge_order": 30,
    "mapSizeExponent": null,
    "fetch": "https://snaccooperative.org/download?arkid=http://n2t.net/ark:/99166/{identifier}&type=constellation_json",
    "activitystreams": null,

    "harvesterClass": "",
    "fetcherClass": "sources.archives.snac.fetcher.SNACFetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.archives.snac.mapper.SNACMapper",
    "reconcilerClass": "",


    "cycleBreakPath": "",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "",
    "remote_dump_files": []
}

=== project-lux/data-pipeline/configs/japansh.json
{
    "name": "japansh",
    "type": "external",
    "namespace": "http://id.ndl.go.jp/auth/ndlsh/",
    "matches": ["id.ndl.go.jp/auth/ndlsh/"],
    "wikidata_property": ["P349"],
    "merge_order": 24,
    "mapSizeExponent": null,
    "fetch": "http://id.ndl.go.jp/auth/ndlsh/{identifier}.json",
    "activitystreams": null,
    
    "harvesterClass": "",
    "fetcherClass": "sources.libraries.japan.fetcher.JapanShFetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.libraries.japan.mapper.JapanShMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",


    "dump_file_subdir": "",
    "remote_dump_files": [
        ""
    ]

}

=== project-lux/data-pipeline/configs/dnb.json
{
    "name": "dnb",
    "type": "external",
    "namespace": "https://d-nb.info/gnd/",
    "matches": ["d-nb.info/gnd/", "hub.culturegraph.org/entityfacts/", 
		"d-nb.info/standards/vocab/gnd/"],
    "wikidata_property": ["P227"],
    "merge_order": 21,
    "mapSizeExponent": null,
    "fetch": "https://hub.culturegraph.org/entityfacts/{identifier}",
    "activitystreams": null,
    
    "harvesterClass": "",
    "fetcherClass": "sources.libraries.dnb.fetcher.DnbFetcher",
    "loaderClass": "sources.libraries.dnb.loader.DnbLoader",
    "indexLoaderClass": "",
    "mapperClass": "sources.libraries.dnb.mapper.DnbMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "dnb_cycle_breaks.json",
    "dumpFilePath": "dnb/authorities-gnd_entityfacts.jsonld.gz",
    "remoteDumpFile": "https://data.dnb.de/opendata/authorities_entityfacts.jsonld.gz",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "dnb",
    "remote_dump_files": [
        "https://data.dnb.de/opendata/authorities-gnd-sachbegriff_lds.jsonld.gz",
        "https://data.dnb.de/opendata/authorities-gnd_entityfacts.jsonld.gz",
        "https://data.dnb.de/opendata/mapping-authorities-gnd-lcsh-ram_lds.jsonld.gz"
    ]
}

=== project-lux/data-pipeline/configs/ror.json
{
    "name": "ror",
    "type": "external",
    "namespace": "https://ror.org/",
    "matches": ["/ror.org/"],
    "wikidata_property": ["P6782"],
    "merge_order": 33,
    "mapSizeExponent": null,
    "fetch": "https://api.ror.org/organizations/{identifier}",
    "activitystreams": null,

    "harvesterClass": "",
    "fetcherClass": "",
    "loaderClass": "sources.general.ror.loader.RorLoader",
    "indexLoaderClass": "",
    "mapperClass": "sources.general.ror.mapper.RorMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "",
    "dumpFilePath": "ror/v1.36-2023-11-08-ror-data.json",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "ror",
    "remote_dump_files": []

}

=== project-lux/data-pipeline/configs/wikimedia.json
{
    "name": "wikimedia",
    "type": "external",
    "namespace": "http://commons.wikimedia.org/",
    "matches": ["commons.wikimedia.org"],
    "wikidata_property": [""],
    "merge_order": null,
    "mapSizeExponent": null,
    "fetch": "https://en.wikipedia.org/w/api.php?action=query&prop=imageinfo&iiprop=extmetadata&titles=File:{identifier}&format=json",
    "activitystreams": null,

    "harvesterClass": "",
    "fetcherClass": "sources.general.wikimedia.fetcher.WmFetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.general.wikimedia.mapper.WmMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",
    
    "dump_file_subdir": "",
    "remote_dump_files": [
        ""
    ]
}

=== project-lux/data-pipeline/configs/lcsh.json
{
    "name": "lcsh",
    "type": "external",
    "namespace": "http://id.loc.gov/authorities/subjects/",
    "matches": ["id.loc.gov/authorities/subjects/"],
    "wikidata_property": ["P244"],
    "merge_order": 14,
    "mapSizeExponent": null,
    "fetch": "http://id.loc.gov/authorities/subjects/{identifier}.json",
    "activitystreams": [
        "https://id.loc.gov/authorities/subjects/activitystreams/feed"
    ],

    "harvesterClass": "",
    "fetcherClass": "sources.authorities.lc.fetcher.LcshFetcher",
    "loaderClass": "sources.authorities.lc.loader.LcLoader",
    "indexLoaderClass": "sources.authorities.lc.index_loader.LCIndexLoader",
    "mapperClass": "sources.authorities.lc.mapper.LcshMapper",
    "reconcilerClass": "sources.authorities.lc.reconciler.LcshReconciler",

    "cycleBreakPath": "lcsh_cycle_breaks.json",
    "dumpFilePath": "lcsh/subjects.madsrdf.jsonld.gz",
    "remoteDumpFile": "",
    "externalLinksPath": "lcsh/external_links.nt",
    "reconcileDumpPath": "",
    "reconcileDbPath": "label_to_lcsh.lmdb",
    "inverseEquivDbPath": "id_to_lcsh.lmdb",

    "dump_file_subdir": "lcsh",
    "remote_dump_files": [
        "https://lds-downloads.s3.amazonaws.com/authorities/subjects.madsrdf.jsonld.gz"
    ]
}

=== project-lux/data-pipeline/configs/homosaurus.json
{
    "name": "homosaurus",
    "type": "external",
    "namespace": "https://homosaurus.org/v3/",
    "matches": ["https://homosaurus.org/v3/"],
    "wikidata_property": ["P6417"],
    "merge_order": 35,
    "mapSizeExponent": null,
    "fetch": "https://homosaurus.org/v3/{identifier}.jsonld",
    "activitystreams": null,

    "harvesterClass": "",
    "fetcherClass": "sources.authorities.homosaurus.fetcher.HomosaurusFetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.authorities.homosaurus.mapper.HomosaurusMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "homosaurus",
    "remote_dump_files": [
        "https://homosaurus.org/v3.jsonld"
    ]

}
