=== project-lux/data-pipeline/configs/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "type": { "type": "string", "enum": ["external", "internal"] },
    "namespace": { "type": "string", "format": "uri" },
    "matches": {
      "type": "array",
      "items": { "type": "string" }
    },
    "wikidata_property": {
      "type": "array",
      "items": { "type": "string", "minLength": 0 }
    },
    "merge_order": {
      "type": ["integer", "null"],
      "minimum": 1
    },
    "mapSizeExponent": {
      "type": ["integer", "null"],
      "minimum": 1
    },
    "fetch": { "type": "string", "format": "uri-template" },
    "activitystreams": {
      "type": ["array", "null"],
      "items": {
        "type": "string",
        "format": "uri",
        "minLength": 0
      }
    },
    "harvesterClass": {"type": "string", "minLength": 0},    
    "fetcherClass": { "type": "string", "minLength": 0},
    "loaderClass": { "type": "string", "minLength": 0 },
    "indexLoaderClass": { "type": "string", "minLength": 0},
    "mapperClass": { "type": "string", "minLength": 0 },
    "reconcilerClass": { "type": "string", "minLength": 0},


    "cycleBreakPath": { "type": "string", "pattern": "\\.json$|^$", "minLength": 0 },
    "dumpFilePath": { "type": "string", "pattern": "\\.(jsonld|json|tar)\\.gz$|\\.jsonld$|\\.json$|\\.marcxml\\.zip$|\\.db$|\\.xml\\.gz$|^$", "minLength": 0 },
    "remoteDumpFile": { "type": "string", "format": "uri", "minLength": 0 },
    "externalLinksPath": { "type": "string", "minLength": 0 },
    "reconcileDumpPath": { "type": "string", "minLength": 0 },
    "reconcileDbPath": { "type": "string", "minLength": 0 },
    "inverseEquivDbPath": { "type": "string", "pattern": "\\.lmdb$|^$", "minLength": 0 },
    "dump_file_subdir": { "type": "string", "minLength": 0 },
    "remote_dump_files": {
      "type": "array",
      "items": { "type": "string", "format": "uri", "minLength": 0 }
    }
  },
  "required": [
    "name",
    "type",
    "namespace",
    "matches",
    "wikidata_property",
    "merge_order",
    "mapSizeExponent",
    "fetch",
    "activitystreams",
    "harvesterClass",
    "fetcherClass",
    "loaderClass",
    "indexLoaderClass",
    "mapperClass",
    "reconcilerClass",
    "cycleBreakPath",
    "dumpFilePath",
    "remoteDumpFile",
    "externalLinksPath",
    "reconcileDumpPath",
    "reconcileDbPath",
    "inverseEquivDbPath",
    "dump_file_subdir",
    "remote_dump_files"
],
  "additionalProperties": false
}

=== project-lux/data-pipeline/configs/geonames.json
{
    "name": "geonames",
    "type": "external",
    "namespace": "https://sws.geonames.org/",
    "matches": ["geonames.org/"],
    "wikidata_property": ["P1566"],
    "merge_order": 41,
    "mapSizeExponent": null,
    "fetch": "https://sws.geonames.org/{identifier}/about.rdf",    
    "activitystreams": null,
    
    "harvesterClass": "",
    "fetcherClass": "sources.general.geonames.fetcher.GnFetcher",
    "loaderClass": "sources.general.geonames.loader.GnLoader",
    "indexLoaderClass": "",
    "mapperClass": "sources.general.geonames.mapper.GnMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "geonames_cycle_breaks.json",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "geonames",
    "remote_dump_files": [
        "https://download.geonames.org/export/dump/allCountries.zip", 
        "https://download.geonames.org/export/dump/alternateNamesV2.zip",
        "https://download.geonames.org/export/dump/hierarchy.zip"
    ]
}

=== project-lux/data-pipeline/configs/wof.json
{
    "name": "wof",
    "type": "external",
    "namespace": "http://data.whosonfirst.org/",
    "matches": ["whosonfirst.org/"],
    "wikidata_property": ["P6766"],
    "merge_order": 40,
    "mapSizeExponent": null,
    "fetch": "https://data.whosonfirst.org/",    
    "activitystreams": null,

    "harvesterClass": "",
    "fetcherClass": "sources.general.wof.fetcher.WofFetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.general.wof.mapper.WofMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "wof_cycle_breaks.json",
    "dumpFilePath": "wof/latest_wof.db",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "wof",
    "remote_dump_files": [
        "https://data.geocode.earth/wof/dist/sqlite/whosonfirst-data-admin-latest.db.bz2"
    ]

}

=== project-lux/data-pipeline/configs/bne.json
{
    "name": "bne",
    "type": "external",
    "namespace": "https://datos.bne.es/resource/",
    "matches": ["datos.bne.es/resource/"],
    "wikidata_property": ["P950"],
    "merge_order": 22,
    "mapSizeExponent": null,
    "fetch": "https://datos.bne.es/resource/{identifier}.jsonld",
    "activitystreams": null,
    
    "harvesterClass": "",
    "fetcherClass": "process.base.fetcher.Fetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.libraries.bne.mapper.BneMapper",
    "reconcilerClass": "",
    
    "cycleBreakPath": "bne_cycle_breaks.json",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",


    "dump_file_subdir": "bne",
    "remote_dump_files": [
        "https://www.bne.es/media/datosgob/catalogo-autoridades/entidad/entidad-JSON.zip",
        "https://www.bne.es/media/datosgob/catalogo-autoridades/materia/materia-JSON.zip",
        "https://www.bne.es/media/datosgob/catalogo-autoridades/geografico/geografico-JSON.zip",
        "https://www.bne.es/media/datosgob/catalogo-autoridades/persona/persona-JSON.zip"

    ]


}

=== project-lux/data-pipeline/configs/aat.json
{
    "name": "aat",
    "type": "external",
    "namespace": "http://vocab.getty.edu/aat/",
    "matches": ["vocab.getty.edu/aat/"],
    "wikidata_property": ["P1014"],
    "merge_order": 10,
    "mapSizeExponent": null,
    "fetch": "https://vocab.getty.edu/aat/{identifier}.jsonld",
    "activitystreams": ["https://data.getty.edu/vocab/activity-stream"],
    
    "harvesterClass": "sources.authorities.getty.harvester.GettyHarvester",
    "fetcherClass": "",
    "loaderClass": "",
    "indexLoaderClass": "process.base.index_loader.LmdbIndexLoader",
    "mapperClass": "sources.authorities.getty.mapper.AatMapper",
    "reconcilerClass": "sources.authorities.getty.reconciler.AatReconciler",
    
    
    "cycleBreakPath": "aat_cycle_breaks.json",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "label_to_aat.lmdb",
    "inverseEquivDbPath": "",

    "dump_file_subdir": "",
    "remote_dump_files": [
        ""
    ]

    
}

=== project-lux/data-pipeline/configs/japan.json
{
    "name": "japan",
    "type": "external",
    "namespace": "http://id.ndl.go.jp/auth/ndlna/",
    "matches": ["id.ndl.go.jp/auth/ndlna/"],
    "wikidata_property": ["P349"],
    "merge_order": 23,
    "mapSizeExponent": null,
    "fetch": "http://id.ndl.go.jp/auth/ndlna/{identifier}.json",    
    "activitystreams": null,
    
    "harvesterClass": "",
    "fetcherClass": "sources.libraries.japan.fetcher.JapanFetcher",
    "loaderClass": "",
    "indexLoaderClass": "",
    "mapperClass": "sources.libraries.japan.mapper.JapanMapper",
    "reconcilerClass": "",

    "cycleBreakPath": "",
    "dumpFilePath": "",
    "remoteDumpFile": "",
    "externalLinksPath": "",
    "reconcileDumpPath": "",
    "reconcileDbPath": "",
    "inverseEquivDbPath": "",


    "dump_file_subdir": "",
    "remote_dump_files": []

}
